services:
  castopod_nginx:
    build: ./docker/production/nginx
    hostname: castopod_nginx
    container_name: castopod_nginx
    volumes:
      - castopod-media:/var/www/castopod/public/media
    ports:
      - 80:80
    depends_on:
      - castopod
    networks:
      - castopod

  castopod:
    image: castopod/castopod:1.13.4
    container_name: "castopod"
    # build:
    #   context: .
    #   dockerfile: ./docker/production/castopod/Dockerfile
    volumes:
      - castopod-media:/var/www/castopod/public/media
      - ./app:/var/www/castopod/app
      - ./themes:/var/www/castopod/themes
      - ./modules:/var/www/castopod/modules
      - ./docker/production/common/prepare_environment.sh:/prepare_environment.sh
      # - ./.env:/var/www/castopod/.env
    environment:
      MYSQL_DATABASE: castopod
      MYSQL_USER: castopod
      MYSQL_PASSWORD: gUTp3mKDwtCtnXwhWvL
      CP_BASEURL: "http://localhost"
      CP_ANALYTICS_SALT: znTQtrxuNgfWeZpdM3ohcYFLXXCXfjzsy
      CP_CACHE_HANDLER: redis
      CP_REDIS_HOST: redis
      CP_REDIS_PASSWORD: ervKEJoNqUUbk3pQepA
      # CI_ENVIRONMENT: development
      CP_DISABLE_HTTPS: 1
      restapi_enabled: 1
      restapi_basicAuthUsername: podcastadmin
      restapi_basicAuthPassword: Em>7/PN(JwA8HmkRa2m
      restapi_basicAuth: 1
      CP_EMAIL_FROM: no-reply@ficade.fr
      CP_EMAIL_SMTP_HOST: smtp-hve.office365.com
      CP_EMAIL_SMTP_PORT: 587
      CP_EMAIL_SMTP_USERNAME: no-reply@ficade.fr
      CP_EMAIL_SMTP_PASSWORD: 2Ws6Y0uClXoM407i
      CP_EMAIL_SMTP_CRYPTO: tls
    networks:
      - castopod
      - castopod-db
    ports:
      - 9000:8000
    restart: unless-stopped

  mariadb:
    image: mariadb:11.2
    container_name: "castopod-mariadb"
    networks:
      - castopod-db
    volumes:
      - castopod-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: q4nvBZjMMLwaGWDpKn
      MYSQL_DATABASE: castopod
      MYSQL_USER: castopod
      MYSQL_PASSWORD: gUTp3mKDwtCtnXwhWvL
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: "castopod-redis"
    command: --requirepass ervKEJoNqUUbk3pQepA
    volumes:
      - castopod-cache:/data
    networks:
      - castopod

volumes:
  castopod-media:
  castopod-db:
  castopod-cache:

networks:
  castopod:
  castopod-db:
